### ISSUE TITLE
Conversion d'unités

### ISSUE THREAD

**Issue by BFECLucasMoreau** [Bureau-du-Forestier-en-chef/MoSiR#10]
**Kilogramme to tonne**
1000 kg = 1t
1kg = 0.001 t

--------------------------

**Comment passer d'une quantité de C d'un GES à une quantité de GES ?**

1 C de CO2 = 3.6667 CO2
1 C de CH4 = 1.3333 CH4
1 C de CO = 2.3333 CO

--------------------------

**Potentiel de réchauffement global (PRG 100ans) :** À définir par l'utilisateur dans le fichier d'intrant ?
Sert à déterminer une quantité en équivalent CO2 (CO2eq) à partir d'une quantité donnée d'un GES donné
Par défaut : PRG 100ans uniquement
CO2 = 1
CH4 = 28 (IPPC AR5)
N2O = 265 (IPPC AR5)

Pas de PRG pour le CO, il se transforme au bout de quelques mois en CO2, donc par défaut je pense qu'on peut mettre PRG =1

**Comment by Landry-G** [comment]
Permis en ce moment : kgC ou tC -> kgC, tC, tCO2eq, w/m2
Équation de la masse dans le script, facteur radiatif dans le fichier excel MoSiR\RadiativeForcing\Dynco2_Base.xlsx
Seulement CO2, CH4, N2O et CO de disponible pour l'instant
