### ISSUE TITLE
Calcul forçage radiatif

### ISSUE THREAD

**Issue by BFECLucasMoreau** [Bureau-du-Forestier-en-chef/MoSiR#12]
Mettre en place le calcul du forçage radiatif (FR) pour le show de boucane.

**Implémenter le calcul (Besoin du fichier d'intrants, Excel ?) :**
Le calcul ne se fait que selon les demandes du fichier d'input.

Pour calculer le FR il faut tout d'abord transformer les kgC (ou les tC) de GES annuel en kg de GES annuel (voir issue #10 ).

=> Les résultats en FR seront-ils annuels ou en cumulatifs? Choix de l'utilisateur ?

**Comment by BFECLucasMoreau** [comment]
Regarder pour mettre à jour les intrants (voir protocole crédit carbone forestier du ministère de l'environnement)

**Comment by Landry-G** [comment]
Possible d'avoir l'annuel ou le cumulatif lorsque mentionner dans le reporting. Gas disponibles pour l'instant: CO2, CH4, N2O et CO. Fichier dans MoSiR\RadiativeForcing\Dynco2_Base.xlsx
