### ISSUE TITLE
Modifier les % entre les nodes de Miro de manière dynamique et surtout plus ergonomique

### ISSUE THREAD

**Issue by BFECLucasMoreau** [Bureau-du-Forestier-en-chef/MoSiR#14]
Le changement des % entre les nodes de Miro se fait actuellement de manière non optimale (Valeur année 1,Valeur année2, etc. et si horizon de simulation plus grand que le nombre d'années inscrit, la valeur de la dernière année est utilisée jusqu'en fin d'horizon).

Peut-on trouver un moyen plus ergonomique de faire des modifications?

Fichier d'intrant ? Comment faire le lien avec le Miro ?
Directement dans Miro ?

**Comment by Landry-G** [comment]
Sera dans 1.0.1
