### ISSUE TITLE
Mathématique de dégradation

### ISSUE THREAD

**Issue by Landry-G** [Bureau-du-Forestier-en-chef/MoSiR#2]
Implémenter l'option de pouvoir choisir l'équation mathématique de dégradation pour les nodes concernées :

Mettre d'une part le choix entre exponentielle et Chi-square. La valeur pourrait être flaggée dans la valeur du temps de demi-vie dans le json, par exemple : Dépotoir [c35] = 35 ans, avec l'équation Chi-square

Par la suite, vérifier la possibilité de transformer un string en équation mathématique pour donner l'option à l'utilisateur d'écrire sa propre formule : https://stackoverflow.com/questions/30775453/converting-a-string-into-equation-and-resolve-it

**Comment by BFECLucasMoreau** [comment]
![Capture_ExpDegradation](https://github.com/Bureau-du-Forestier-en-chef/MoSiR/assets/143514415/22c34dd9-f78f-4c6d-b31c-2b312dd65eac)
===> Equation exponentielle

===> Je cherche celle du Chi-square

**Comment by BFECLucasMoreau** [comment]
Cette loi se calcule très facilement avec Excel en utilisant : LOI.KHIDEUX.N

Avec k(degrés de liberté) = Tmoyen de dégradation + 2

Un package Python doit certainement exister pour faire la même chose !

**Comment by BFECLucasMoreau** [comment]
Doit on écrire la formule mathématique de dégradation ou fournir au calculateur une courbe de la matière restante selon le temps de dégradation ?

Si la courbe doit être écrite, il faut qu'elle soit complète sur l'horizon de temps. Problématique qu'on ne retrouve pas avec la formule.

Peut on avoir le choix entre les deux ?

**Comment by BFECLucasMoreau** [comment]
[Calcul_Degradation.xlsx](https://github.com/Bureau-du-Forestier-en-chef/MoSiR/files/13218230/Calcul_Degradation.xlsx)

**Comment by BFECLucasMoreau** [comment]
Articles sur les différentes courbes de dégradation :

1 - Marland_2010 (Pose la question initiale)

2-  Cherubini_2012 (Utilisation Chi-square)

3- Bates_2017 (Déterminer les valeurs des variables d'une distribution Gamma)
=> Exponentielle + Gamma standard + K=2 + Chi-square

**Comment by BFECLucasMoreau** [comment]
Excel basé sur Bates_2017 pour déterminer les variables nécessaire à une dégradation Gamma selon la demi vie ou le temps de vie moyen voulu :

[Calcul_Degradation.xlsx](https://github.com/Bureau-du-Forestier-en-chef/MoSiR/files/13218348/Calcul_Degradation.xlsx)

**Comment by BFECLucasMoreau** [comment]
**Utilisation d'une équation Gamma unique basée sur Bates_2017**

Exemple d'intrant :




L'équation va varier selon la valeurs des variables déterminé manuellement grâce au fichier Excel suivant :
[Calcul_Degradation.xlsx](https://github.com/Bureau-du-Forestier-en-chef/MoSiR/files/13218373/Calcul_Degradation.xlsx)

La question de flagger quelle équation correspond à quelle node reste identique !

**Comment by BFECLucasMoreau** [comment]
Exemple : T1/2 = 30 ans.
![image](https://github.com/Bureau-du-Forestier-en-chef/MoSiR/assets/143514415/85eb61b6-b8a8-4d4d-8515-c02277406449)

**Comment by BFECLucasMoreau** [comment]
Image graph

**Comment by BFECLucasMoreau** [comment]
Package Python possible : https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gamma.html

**Comment by BFECLucasMoreau** [comment]
Nomenclature dans les node Miro à changer :

Remplacer Half-life[35] par gamma(k=X,theta=Y,halflife=35)
L'utilisateur doit déterminer ses variables **k** et **theta** avec le fichier Excel.
