### ISSUE TITLE
Version portable MoSiR

### ISSUE THREAD

**Issue by BFECLucasMoreau** [Bureau-du-Forestier-en-chef/MoSiR#25]
Go for it !

**Comment by Landry-G** [comment]
python -m nuitka 
--standalone 
--onefile 
--onefile-windows-splash-screen-image 
--include-package-data=MoSiR
--include-package-data=pyvis 
--windows-icon-from-ico
--company-name="Bureau du Forestier en chef"
--product-name=MoSiR
--product-version=0.9.0
--copyright="Gouvernement du Québec"
