### ISSUE TITLE
Suprimer dans l'application MoSiR une architecture qui est chargée mais qu'on ne veut plus interroger

### ISSUE THREAD

**Issue by BFECLucasMoreau** [Bureau-du-Forestier-en-chef/MoSiR#30]
Si on charge plusieurs tableaux Miro, arrivé dans la configuration du fichier output (résultats que l'on souhaite avoir) on doit poser des questions à tous les graphs sinon ça ne marche pas. Pourrait-on avoir la possibilité de supprimer un graph qui a été chargé ?

**Comment by Landry-G** [comment]
Fixed

Lorsque l'utilisateur load un autre json, par Miro ou l'import, la cache de graph est vidé pour éviter des erreurs dans le reporting. C'était la solution la plus simple comparativement à créer un bouton pour supprimer un graph en plus d'implémenter une solution si on voulait lancer un report identique pour deux graph en provenance de json différents
