### ISSUE TITLE
Charactères spéciaux HTLM dans Miro

### ISSUE THREAD

**Issue by Landry-G** [Bureau-du-Forestier-en-chef/MoSiR#6]
Les charactères spéciaux dans Miro ne sont pas traduit correctement dans le JSON suite à l'exportation, notamment '&' qui se trouve à être un charactère utilisé en HTML. Il faut donc éviter l'utilisation de tel charactères: 
https://www.w3schools.com/html/html_entities.asp

- L'inclure dans la doc éventuellement

- Pour Lucas :  Changer les charactères spéciaux dans Miro, principalement '&' dans pâte et papier. 

- Pour Guillaume : Préparer un message d'erreur lorsqu'un utilisateur écrit un charactère utilisé en HTML

**Comment by gcyr** [comment]
Je vais plûtot corriger de mon côté le code avec la réponse votez à 710 ici! Lucas change rien 
https://stackoverflow.com/questions/2087370/decode-html-entities-in-python-string
